compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.1.cjs


injectEnvironmentFiles:
  - .env
  - .env.yarn?
  - .env.local?

npmScopes:
 fortawesome:
   npmAlwaysAuth: true
   npmRegistryServer: "https://npm.fontawesome.com/"
   npmAuthToken: ${FONTAWESOME_PACKAGE_TOKEN}
 awesome.me:
   npmAlwaysAuth: true
   npmRegistryServer: "https://npm.fontawesome.com/"
   npmAuthToken: ${FONTAWESOME_PACKAGE_TOKEN}